### ISSUE TITLE
[FEATURE] 이메일 로그인

### ISSUE THREAD

**Issue by ji-yeon224** [ji-yeon224/WeSpace#11]
## Description
이메일 로그인 구현하기

## Todo
- [x]  이메일 로그인 화면 구성
- [x]  이메일 로그인 로직 구현
- [x]  로그인 성공 시 유저 정보 조회
- [x]  화면 전환
