### ISSUE TITLE
[FEATURE] Email Join

### ISSUE THREAD

**Issue by ji-yeon224** [ji-yeon224/WeSpace#5]
## Description
이메일 회원가입 하기

## Todo
- [x]  회원 가입 화면 전환 구현
- [x]  회원가입 뷰 구성
- [x]  이메일 유효성 검증
- [x]  이메일 중복 체크
- [x]   가입 버튼 클릭 시 입력 값 유효성 체크
- [x]  토스트 메세지 
- [x]  회원가입
